<?php namespace Api;

use Services\User\UserService;

/**
 * Class UserController
 * @package Api;
 */
class UserController extends BaseController
{
    /**
     * @var UserService $service
     */
    protected $service;

    public function initialize()
    {
        $this->service = new UserService();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function getUserAction($slug)
    {
        if ($user = $this->service->getUserBySlug($slug)) {

            echo strtotime('24-09-1993');
            exit();

            $data = ($slug == 'demo')
                ? $this->buildDemoUser($user)
                : $this->buildResponse($user);

            return $this->response(200, 'OK', $data);
        }

        return $this->response(404, 'OK', ['message' => 'User not found']);
    }

    private function buildDemoUser($user)
    {
        $data = (object)[
            'slug' => $user->slug,
            'firstName' => $user->firstName,
            'lastName' => $user->lastName,
            'age' => '22',
            'gym' => (object)[
                'name' => $user->Gym->name,
                'location' => $user->Gym->location,
            ],
            'time' => (object)[
                'average' => (object)[
                    'session' => '1:38:29',
                    'active' => '1:04:23'
                ]
            ]
        ];

        return $this->buildResponse($data);
    }

    private function buildResponse($user)
    {
        return [
            'slug' => $user->slug,
            'user' => [
                'firstName' => $user->firstName,
                'lastName' => $user->lastName,
                'age' => $user->age
            ],
            'gym' => [
                'name' => $user->gym->name,
                'location' => $user->gym->location,
            ],
            'sessions' => [

            ],
            'time' => [
                'average' => [
                    'session' => $user->time->average->session,
                    'active' => $user->time->average->active
                ]
            ]
        ];
    }
}
